steps:
  - name: ‘gcr.io/cloud-builders/docker’
    args: [‘build’, ‘-t’, ‘gcr.io/dtumlops-337915/dockers', '.', '-f', 'Dockerfile']

  - name: ‘gcr.io/cloud-builders/docker’
    args: [‘push’, ‘gcr.io/dtumlops-337915/dockers']
